meta_product_name: "Group Up"
meta_title: "group up - don't stay locked down"
meta_description: "group up is the online meeting point for friends to decided when and where they can meet up with each other"
meta_image: "cover.png" # should exist in `app/assets/images/`
